"""Voltando Preco

Revision ID: 7be5de81c81c
Revises: 86fd16aaea08
Create Date: 2026-06-15 16:30:09.281265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be5de81c81c'
down_revision: Union[str, Sequence[str], None] = '86fd16aaea08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('preco', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'preco')
    # ### end Alembic commands ###
