"""Socorro

Revision ID: 86fd16aaea08
Revises: fee2ab8713c4
Create Date: 2026-06-15 16:28:52.488709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86fd16aaea08'
down_revision: Union[str, Sequence[str], None] = 'fee2ab8713c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'preco')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('preco', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
